version: '3.9'
services:
  dev-db:
    image: postgres:16
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nest

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - dev-db

  test-db:
    image: postgres:16
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nest
  test-pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - test-db
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
    ports:
      - "5051:80"

