version: '3.9'
services:
  dev-db:
    image: postgres:16
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nest
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - dev-db
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
    ports:
      - "5050:80"

